app.py
from flask import Flask, request, render_template

from views import index_app
from views import catalog_app
from views import contact_app

app = Flask(__name__)
app.register_blueprint(index_app)
app.register_blueprint(catalog_app)
app.register_blueprint(contact_app)


@app.route("/", methods=["GET", "POST"])
def index():
    name = "World"
    if request.method == "POST":
        name = request.form.get('name', 'World')
    return render_template("index.html", name=name)


@app.route("/contact", methods=["GET", "POST"])
def contact():
    return render_template("contact.html")


# @app.route("/catalog", methods=["GET", "POST"])
# def catalog():
#     return f"<h1>Catalog</h1>"

main.py
from app import app


if __name__ == '__main__':
    app.run(debug=True)

views/__init__.py
from .index import index_app
from .catalog import catalog_app
from .contact import contact_app

views/catalog.py
from flask import Blueprint, render_template, request, jsonify
from werkzeug.exceptions import BadRequest

catalog_app = Blueprint("catalog_app", __name__)


def get_default_products():
    return {
        1: "Развивающие книги",
        2: "Конструкторы",
        3: "Раскраски"
    }


PRODUCTS = get_default_products()


@catalog_app.route("/catalog")
def catalog_list():
    return render_template("catalog/index.html", products=PRODUCTS)


@catalog_app.route("/<int:product_id>/", methods=['GET', 'DELETE'])
def product_detail(product_id: int):
    try:
        product_name = PRODUCTS[product_id]
    except KeyError:
        raise BadRequest(f"Invalid product id #{product_id}")

    if request.method == 'DELETE':
        PRODUCTS.pop(product_id)
        return jsonify(ok=True)

    return render_template(
        "catalog/detail.html",
        product_id=product_id,
        product_name=product_name
    )


@catalog_app.route("/recover/", methods=["POST"])
def recover_products():
    PRODUCTS.update(get_default_products())
    return jsonify(ok=True)

views/contact.py
from flask import Blueprint, render_template

contact_app = Blueprint("contact_app", __name__)


@contact_app.route("/contact")
def contact_page():
    return render_template("contact.html")

views/index.py
from flask import Blueprint, render_template

index_app = Blueprint("index_app", __name__)


@index_app.route("/")
def index_page():
    return render_template("index.html")

templates/base.html
<!DOCTYPE html>
<html lang="ru">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>
        {% block title %}
        {% endblock %}
    </title>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">

</head>
<body>
    <div class="wrapper">
		<header class="header">
			<div class="header__container container">
				<div class="header__logo header__logo--logo">
					<a href="{{ url_for('index_app.index_page') }}" class="logo">
						iToys
					</a>
				</div>
				<div class="header__menu header__menu--menu">
					<nav class="menu">
						<ul class="menu__list">
							<li class="menu__list-item">
								<a href="{{ url_for('index_app.index_page') }}" class="menu__list-item-link">Главная</a>
							</li>
							<li class="menu__list-item">
								<a href="{{ url_for('catalog_app.catalog_list') }}" class="menu__list-item-link">Каталог</a>
							</li>
							<li class="menu__list-item">
								<a href="{{ url_for('contact_app.contact_page') }}" class="menu__list-item-link">Связаться</a>
							</li>
						</ul>
					</nav>
				</div>
				<div class="header__phone header__phone--phone">
					<a href="tel:911" class="phone">8 800 555 55 55</a>
				</div>
			</div>
		</header>
    {% block body %}
    {% endblock %}
        <footer class="footer">
			<div class="footer__container container">
				<div class="footer__rights">
					<div class="footer__rights-logo footer__copy-logo--logo">
						<a href="{{ url_for('index_app.index_page') }}" class="logo">iToys</a>
					</div>
					<div class="footer__rights-copyright">© 2020 OOO "iToys ltd."</div>
				</div>
				<div class="footer__nav footer__nav--menu">
					<nav class="menu">
						<ul class="menu__list">
							<li class="menu__list-item">
								<a href="{{ url_for('index_app.index_page') }}" class="menu__list-item-link">Главная</a>
							</li>
							<li class="menu__list-item">
								<a href="{{ url_for('catalog_app.catalog_list') }}" class="menu__list-item-link">Каталог</a>
							</li>
							<li class="menu__list-item">
								<a href="{{ url_for('contact_app.contact_page') }}" class="menu__list-item-link">Связаться</a>
							</li>
						</ul>
					</nav>
				</div>
				<div class="footer__phone footer__phone--phone">
					<a href="tel:911" class="phone">8 800 555 55 55</a>
				</div>
			</div>
		</footer>
	</div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg=="
        crossorigin="anonymous"></script>
{% block after_body %}
{% endblock %}
</body>
</html>

templates/catalog/detail.html
{% extends 'base.html' %}

{% block title %}
    Товар
{% endblock %}

{% block body %}
    <div class="container">
        <div class="catalog__item-product">
            <div class="catalog__item-product-image">
                <img src="{{ url_for('static', filename='/img/content/page.jpg') }}"
                     alt="" class="catalog__item-product-img">

            </div>
            <div class="catalog__item-product-text">
                <h3 class="catalog__item-product-title">{{ product_name }}</h3>
                <div class="catalog__item-product-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, maxime ex labore temporibus sunt.</div>
                <div class="catalog__item-product-button">
                    <button id="delete-product" type="button" class="catalog__item-product--btn cta__buy">Удалить</button>
                </div>
            </div>
        </div>
    </div>


{% endblock %}
{% block after_body %}
  <script>
  $(function() {
      $('#delete-product').click(function () {
          $.ajax({
              method: 'DELETE',
              success: function (res) {
                console.log(res)
                console.log(res.data)
              },
              error: function (err) {
                console.error(err)
              },
              complete: function () {
                window.location = '{{ url_for('catalog_app.catalog_list') }}'
              },
          })
      })
  });
  </script>
{% endblock %}

templates/catalog/index.html
{% extends 'base.html' %}

{% block title %}
Каталог развивающих игрушек
{% endblock %}

{% block body %}
    <div class="maincontent">
			<section class="catalog">
				<div class="catalog__container container">
					<h1 class="catalog__title">Каталог развивающих игрушек</h1>
					<div class="catalog__desc">Доставка по всему Миру</div>
                    <div class="catalog__item-product-button">
                        <button id="recover-products" type="button" class="catalog__item-product--btn cta__buy">Восстановить</button>
                    </div>
					<ul class="catalog__list">
						<li class="catalog__item">
							<h2 class="catalog__subtitle">Развитие моторики</h2>
							<ul class="catalog__item-products">
                                {% for product_id in products %}
                                    <li class="catalog__item-product">
                                        <a class="my-2" href="{{ url_for('catalog_app.product_detail', product_id=product_id) }}">
                                            <div class="catalog__item-product-image">
                                                <img src="{{ url_for('static', filename='/img/content/page.jpg') }}"
                                                     alt="" class="catalog__item-product-img">

                                            </div>
                                            <div class="catalog__item-product-text">
                                                <h3 class="catalog__item-product-title">{{ products[product_id] }}</h3>
                                                <div class="catalog__item-product-desc">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, maxime ex labore temporibus sunt.</div>
                                            </div>
                                        </a>
                                    </li>
                                {% endfor %}
							</ul>

						</li>
					</ul>
				</div>
			</section>
		</div>
{% endblock %}
{% block after_body %}
<script>
    $('#recover-products').click(function () {
      $.ajax({
        url: 'recover/',
        method: 'POST',
        success: function (res) {
          console.log(res)
          console.log(res.data)
        },
        error: function (err) {
          console.error(err)
        },
        complete: function () {
          window.location = '{{ url_for('catalog_app.catalog_list') }}'
        },
      })
    })
</script>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block title %}
  Связаться с нами
{% endblock %}

{% block body %}
<div class="maincontent">
    <section class="contact">
        <div class="contact__container container">
            <h1 class="contact__title">Свяжитесь с нами!</h1>
            <form action="" method="post" class="contact__form">
                <input type="email" placeholder="Email" class="contact__input">
                <textarea class="contact__input" placeholder="Напишите здесь" name="msg" cols="30" rows="10"></textarea>
                <button class="contact__btn cta">Отправить</button>
            </form>
        </div>
    </section>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}
  Hello
{% endblock %}

{% block body %}
  <div class="maincontent">
      <section class="hero">
          <div class="hero__container container">
              <h1 class="hero__title">Развивающие игрушки для детей 1-5 лет</h1>
              <div class="hero__desc">Доставка по всему Миру</div>
              <a href="{{ url_for('catalog_app.catalog_list') }}" class="hero__cta cta">Перейти в каталог</a>
          </div>
      </section>
  </div>
{% endblock %}